# Numpy

In [34]:
import numpy as np
print(np.__version__)

1.26.4


In [35]:
my_list = [1, 2, 3, 4, 5] # eine einfache Python-Liste, Tuple wäre z.B. auch möglich
my_array = np.array(my_list)
print(my_array)
isinstance(my_array, np.ndarray)

[1 2 3 4 5]


True

In [36]:
my_array.shape

(5,)

In [37]:
my_array_2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(my_array_2)
my_array_2.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [38]:
# die Anzahl der Dimensionen des Arrays ausgeben
print(my_array_2.ndim)

# die Anzahl der Elemente im Array ausgeben
print(my_array_2.size)

# den Datentyp der im Array gespeicherten Werte ausgeben
print(my_array_2.dtype)

2
9
int32


In [39]:
# Versuch, Datentypen innerhalb eines Arrays zu mischen
my_array_3 = np.array([[1,2,3], [4,5,6], [7,8,"neun"]])
print(my_array_3)

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' 'neun']]


In [40]:
# einen Array aus einem Tupel erzeugen
my_array_4 = np.array((1, 2, 3, 4, 5, 6, 7, 8, 9, 10))

# den erzeugten Array inspizieren
print(my_array_4)
print(my_array_4.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [41]:
# den ein-dimensionalen Array in einen Array mit 5 Zeilen und 2 Spalten konvertieren
my_array_5 = my_array_4.reshape(5, 2)

# den neuen Array inspizieren
print(my_array_5)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [42]:
# den Speicherplatz in Bytes ausgeben, den ein Element des Arrays belegt
print(my_array_5.itemsize)

# die ID für den im RAM belegten Speicher ausgeben
print(my_array_5.data)

4


In [43]:
arr_1 = np.array([1, 2, 3, 4, 5])
arr_2 = np.array([6, 7, 8, 9, 10])

print(arr_1 + arr_2)
print(arr_1 - arr_2)
print(arr_1 * arr_2)
print(arr_1 / arr_2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [44]:
# arithmetisches Mittel
print(np.mean(arr_1))

# Median
print(np.median(arr_2))

# Varianz
print(np.var(arr_1))

# Standardabweichung
print(np.std(arr_1))

3.0
8.0
2.0
1.4142135623730951


In [45]:
# Minimaler Wert
print(np.min(arr_1))

# Maximaler Wert
print(np.max(arr_1))

# Summe aller Werte
print(np.sum(arr_1))

# Anzahl der Werte, die größer sind als das arithmetische Mittel
print(np.sum(arr_1 > np.mean(arr_1)))

1
5
15
2


In [46]:
# Zufallszahlen generieren
my_array_6 = np.random.randn(5)
print(my_array_6)

[-1.03193415 -0.48679383  2.04948245 -1.05494082  0.07240976]


# Pandas
Dreh- und Angelpunkt des pandas-Packages sind die sogenannten Dataframes. Diese stel-
len Datenstrukturen dar, die einen intuitiven Umgang mit tabellarischen Daten erlauben.
Wir können diese Datenstruktur als Tabelle verstehen, bei der die einzelnen Zeilen über
einen Index angesprochen werden können und die Spalten aus sogenannten Series beste-
hen. Letztere stellen eine Datenstruktur in sich dar, welche das Pandas-Package für uns
bereithält. Solch eine Serie stellt, wie gesagt, in aller Regel eine Spalte in einem Dataframe
dar, kann aber auch als losgelöstes Objekt erzeugt und behandelt werden. Innerhalb einer
Serie können nur Elemente vom gleichen Datentyp gespeichert werden (z. B. String, Integer, Date).
Innerhalb eines Dataframes können aber Serien unterschiedlicher Datentypen
vereint werden. So können wir z. B. in einer Spalte des Dataframes ein Datum, in einer
anderen Spalte einen Text und in einer weiteren Spalte einen Integer speichern.

In [47]:
import pandas as pd
import numpy as np
print(pd.__version__)

2.1.4


In [48]:
# zwei Series erzeugen
my_series_1 = pd.Series(np.random.randn(5))
my_series_2 = pd.Series(np.random.randn(5))

# Series spaltenweise zu einem Dataframe verketten
my_df_1 = pd.concat([my_series_1, my_series_2], axis=1)

# Dataframe anzeigen
print(my_df_1)

          0         1
0 -0.351645  0.087469
1 -1.735268 -0.235379
2  1.725546 -1.832659
3 -0.456696 -1.231204
4  0.169496 -0.277960


In [49]:
print(isinstance(my_df_1, pd.DataFrame))

True


In [50]:
# einen Dataframe aus einem Dictionary erzeugen
my_dic = {"Name":['Bernd', 'Silke', 'Claudia'], \
    "Alter":[54, 36, 23], \
    "Lieblingszahl":np.random.randn(3)
    }
my_df_2 = pd.DataFrame(my_dic)

# Dataframe anzeigen
print(my_df_2)

      Name  Alter  Lieblingszahl
0    Bernd     54      -0.119658
1    Silke     36       1.796227
2  Claudia     23       0.486963


In [51]:
# Dataframe mit anderem Index erzeugen
my_df_3 = pd.DataFrame(my_dic, \
index=['1001', '1002', '1003'])

# Dataframe anzeigen
print(my_df_3)

print(my_df_3.index)

         Name  Alter  Lieblingszahl
1001    Bernd     54      -0.119658
1002    Silke     36       1.796227
1003  Claudia     23       0.486963
Index(['1001', '1002', '1003'], dtype='object')


In [52]:
# Daten aus einer CSV-Datei in einen Dataframe laden
dat = pd.read_csv('data/sample_data.csv')

# Dataframe anzeigen
print(dat)

   place  min  max        type public      date      fee resp
0    NaN  2.1  4.8        trad   True       NaN  £200.45   CT
1    NaN  NaN  3.2         NaN  False  1/1/2017  £150.38   AS
2   25.0  2.3  3.3     forrest   True  2/1/2017   £85.07   CT
3   35.0  2.4  NaN        trad    NaN  3/1/2017      NaN   CT
4    NaN  2.1  4.8        trad   True       NaN  £200.45   CT
5   12.0  NaN  3.3     waldorf  False  2/1/2017  £350.96   AS
6   18.0  2.5  NaN     forrest    NaN  4/1/2017      NaN   CT
7   15.0  2.3  4.3  montessori   True  2/1/2017   £85.07   CT


In [53]:
dat.shape

(8, 8)

In [54]:
dat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   place   5 non-null      float64
 1   min     6 non-null      float64
 2   max     6 non-null      float64
 3   type    7 non-null      object 
 4   public  6 non-null      object 
 5   date    6 non-null      object 
 6   fee     6 non-null      object 
 7   resp    8 non-null      object 
dtypes: float64(3), object(5)
memory usage: 644.0+ bytes


In [55]:
dat.describe()

place       min       max
count   5.000000  6.000000  6.000000
mean   21.000000  2.283333  3.950000
std     9.192388  0.160208  0.771362
min    12.000000  2.100000  3.200000
25%    15.000000  2.150000  3.300000
50%    18.000000  2.300000  3.800000
75%    25.000000  2.375000  4.675000
max    35.000000  2.500000  4.800000

In [56]:
# Anzahl der vorkommenden Werte in der resp Spalte anzeigen
dat["resp"].value_counts()

resp
CT    6
AS    2
Name: count, dtype: int64

In [57]:
# Anzahl der fehlenden Werte für jede Spalte anzeigen
dat.isna().sum()

place     3
min       2
max       2
type      1
public    2
date      2
fee       2
resp      0
dtype: int64

In [58]:
# Auf einzelne Spalte zugreifen
dat["fee"]

0    £200.45
1    £150.38
2     £85.07
3        NaN
4    £200.45
5    £350.96
6        NaN
7     £85.07
Name: fee, dtype: object

In [59]:
# Auf einzelnen Wert via loc zugreifen (erst Zeilenindex, dann Spaltenname)
dat.loc[2, 'type']

'forrest'

In [60]:
# Auf einzelnen Wert via iloc zugreifen (erst Zeilenindex, dann Spaltenindex)
dat.iloc[2, 3]

'forrest'

In [61]:
# Auf bestimmten Bereich zugreifen
dat.iloc[2:5, 3:6].values

array([['forrest', True, '2/1/2017'],
       ['trad', nan, '3/1/2017'],
       ['trad', True, nan]], dtype=object)

In [62]:
# Duplizierte Werte anzeigen
dat.duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
dtype: bool

In [63]:
# Duplikate entfernen
dat.drop_duplicates()

place  min  max        type public      date      fee resp
0    NaN  2.1  4.8        trad   True       NaN  £200.45   CT
1    NaN  NaN  3.2         NaN  False  1/1/2017  £150.38   AS
2   25.0  2.3  3.3     forrest   True  2/1/2017   £85.07   CT
3   35.0  2.4  NaN        trad    NaN  3/1/2017      NaN   CT
5   12.0  NaN  3.3     waldorf  False  2/1/2017  £350.96   AS
6   18.0  2.5  NaN     forrest    NaN  4/1/2017      NaN   CT
7   15.0  2.3  4.3  montessori   True  2/1/2017   £85.07   CT

In [64]:
# spaltenweise definieren, wie fehlende Werte ersetzt werden sollen
fill_values = {
    'place': np.nanmedian(dat['place']),
    'min': np.mean(dat['min']),
    'max': np.mean(dat['max']),
    'type': 'trad',
    'public': True,
    'date': '1/1/2017',
    'fee': '£250.00'
}

# fehlende Werte ersetzen
dat.fillna(value=fill_values, inplace=True)

dat

place       min   max        type  public      date      fee resp
0   18.0  2.100000  4.80        trad    True  1/1/2017  £200.45   CT
1   18.0  2.283333  3.20        trad   False  1/1/2017  £150.38   AS
2   25.0  2.300000  3.30     forrest    True  2/1/2017   £85.07   CT
3   35.0  2.400000  3.95        trad    True  3/1/2017  £250.00   CT
4   18.0  2.100000  4.80        trad    True  1/1/2017  £200.45   CT
5   12.0  2.283333  3.30     waldorf   False  2/1/2017  £350.96   AS
6   18.0  2.500000  3.95     forrest    True  4/1/2017  £250.00   CT
7   15.0  2.300000  4.30  montessori    True  2/1/2017   £85.07   CT

In [65]:
# Pfundzeichen in 'fee'-Spalte entfernen und nach 'float' konvertieren
dat['fee'] = dat['fee']\
    .map(lambda x: str(x)[1:])\
    .astype('float')

dat

place       min   max        type  public      date     fee resp
0   18.0  2.100000  4.80        trad    True  1/1/2017  200.45   CT
1   18.0  2.283333  3.20        trad   False  1/1/2017  150.38   AS
2   25.0  2.300000  3.30     forrest    True  2/1/2017   85.07   CT
3   35.0  2.400000  3.95        trad    True  3/1/2017  250.00   CT
4   18.0  2.100000  4.80        trad    True  1/1/2017  200.45   CT
5   12.0  2.283333  3.30     waldorf   False  2/1/2017  350.96   AS
6   18.0  2.500000  3.95     forrest    True  4/1/2017  250.00   CT
7   15.0  2.300000  4.30  montessori    True  2/1/2017   85.07   CT

In [67]:
# Werte ersetzen
rep_dic = {'CT':'City', 'AS':'Ass.'}
dat['resp'].replace(to_replace=rep_dic, inplace=True)

dat

place       min   max        type  public      date     fee  resp
0   18.0  2.100000  4.80        trad    True  1/1/2017  200.45  City
1   18.0  2.283333  3.20        trad   False  1/1/2017  150.38  Ass.
2   25.0  2.300000  3.30     forrest    True  2/1/2017   85.07  City
3   35.0  2.400000  3.95        trad    True  3/1/2017  250.00  City
4   18.0  2.100000  4.80        trad    True  1/1/2017  200.45  City
5   12.0  2.283333  3.30     waldorf   False  2/1/2017  350.96  Ass.
6   18.0  2.500000  3.95     forrest    True  4/1/2017  250.00  City
7   15.0  2.300000  4.30  montessori    True  2/1/2017   85.07  City

In [69]:
# Dataframe als CSV-Datei speichern
dat.to_csv('data/preprocessed_data.csv', encoding="utf-8")