# Numpy

In [1]:
import numpy as np
print(np.__version__)

1.26.4


In [2]:
my_list = [1, 2, 3, 4, 5] # eine einfache Python-Liste, Tuple wäre z.B. auch möglich
my_array = np.array(my_list)
print(my_array)
isinstance(my_array, np.ndarray)

[1 2 3 4 5]


True

In [3]:
my_array.shape

(5,)

In [4]:
my_array_2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(my_array_2)
my_array_2.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [5]:
# die Anzahl der Dimensionen des Arrays ausgeben
print(my_array_2.ndim)

# die Anzahl der Elemente im Array ausgeben
print(my_array_2.size)

# den Datentyp der im Array gespeicherten Werte ausgeben
print(my_array_2.dtype)

2
9
int32


In [6]:
# Versuch, Datentypen innerhalb eines Arrays zu mischen
my_array_3 = np.array([[1,2,3], [4,5,6], [7,8,"neun"]])
print(my_array_3)

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' 'neun']]


In [7]:
# einen Array aus einem Tupel erzeugen
my_array_4 = np.array((1, 2, 3, 4, 5, 6, 7, 8, 9, 10))

# den erzeugten Array inspizieren
print(my_array_4)
print(my_array_4.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [8]:
# den ein-dimensionalen Array in einen Array mit 5 Zeilen und 2 Spalten konvertieren
my_array_5 = my_array_4.reshape(5, 2)

# den neuen Array inspizieren
print(my_array_5)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [9]:
# den Speicherplatz in Bytes ausgeben, den ein Element des Arrays belegt
print(my_array_5.itemsize)

# die ID für den im RAM belegten Speicher ausgeben
print(my_array_5.data)

4


In [10]:
arr_1 = np.array([1, 2, 3, 4, 5])
arr_2 = np.array([6, 7, 8, 9, 10])

print(arr_1 + arr_2)
print(arr_1 - arr_2)
print(arr_1 * arr_2)
print(arr_1 / arr_2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [11]:
# arithmetisches Mittel
print(np.mean(arr_1))

# Median
print(np.median(arr_2))

# Varianz
print(np.var(arr_1))

# Standardabweichung
print(np.std(arr_1))

3.0
8.0
2.0
1.4142135623730951


In [12]:
# Minimaler Wert
print(np.min(arr_1))

# Maximaler Wert
print(np.max(arr_1))

# Summe aller Werte
print(np.sum(arr_1))

# Anzahl der Werte, die größer sind als das arithmetische Mittel
print(np.sum(arr_1 > np.mean(arr_1)))

1
5
15
2


In [13]:
# Zufallszahlen generieren
my_array_6 = np.random.randn(5)
print(my_array_6)

[ 0.48225798  0.65033129 -2.6933601  -0.5338545   0.20451309]
